wifi_ssid: YOUR_SSID
wifi_password: YOUR_WIFI_PASSWORD
web_server_username: admin
web_server_password: admin
# generate yourself new one
# https://esphome.io/components/api.html#configuration-variables
esphome_api_password: jvT5pIBntczkJoXVt9+PFzcuHL8r7alxagnxVtojmb0=
